### ISSUE TITLE
Error while stitching songs with thumbnails

### ISSUE THREAD

**Issue by WerySkok** [pepershukov/ytm-yld#1]
Probably was because of illegal characters in the name. Here's the part of the log

```
[LOG] Opening #16 thumbnail...
[LOG] Cropping #16 thumbnail...
[LOG] Saving #16 thumbnail...
[LOG] Opening #16 song...
[LOG] Setting #16 MP3 metadata title...
[LOG] Setting #16 MP3 metadata artist...
[LOG] Setting #16 MP3 metadata author...
[LOG] Setting #16 MP3 metadata album name...
[LOG] Saving #16 MP3...
[LOG] Opening #16 MP3's metadata...
[LOG] Adding album art to #16 MP3 metadata...
[LOG] Saving #16 MP3...
[LOG] Moving #16 (序幕－デビルマンの歌) song to "C:\Users\werys\Downloads\YouTube Music\songs"...
Traceback (most recent call last):
  File "main.py", line 237, in <module>
  File "playlist_downloader.py", line 168, in download_songs
  File "playlist_downloader.py", line 68, in process_songs
  File "main.py", line 83, in logwrite
  File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 48-57: character maps to <undefined>
[19200] Failed to execute script 'main' due to unhandled exception!
```

**Comment by pepershukov** [comment]
yeah, it indeed was - the reason is that i did not have an exception for such characters - only for ones that windows specifically doesnt allow ([see lines 73-83](https://github.com/pepershukov/ytm-yld/blob/main/playlist_downloader.py#L73-L83)). i will try to add an additional exception and push an update

**Comment by pepershukov** [comment]
@WerySkok, I pushed a hotfix [#5.0.1](https://github.com/pepershukov/ytm-yld/releases/tag/v5.0.1) hopefully fixing this issue! Let me know if it persists or something else wrong happens
